### ISSUE TITLE
Unable to use generated schema in BigQuery due to type problem

### ISSUE THREAD

**Issue by cstrouse** [benjaminestes/crawl#26]
When I use the generated schema format in BigQuery it doesn't allow me to save the table because INT64 is not a supported type. Is this a bug or am I doing something wrong?

![image](https://user-images.githubusercontent.com/849044/68848347-6bfb2d00-068d-11ea-894e-29adb9d250d0.png)

**Comment by benjaminestes** [comment]
Hello @cstrouse — This might be an annoyance with the BiqQuery web interface.

BigQuery used to use "Legacy SQL", which came with certain syntax and [types](https://cloud.google.com/bigquery/data-types). At some point that changed to "Standard SQL", which has different [types](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types).

Standard SQL is the future, and is the default behavior for the command line tools. For reasons I don't fully understand, the web interface uses Legacy SQL. So it expects Legacy SQL names like "INTEGER" instead of "INT64". I don't _think_ that can be toggled.

If you have the CLI installed you can run:

`bq mk my_dataset.my_new_table schema.json`

...and it will create an empty table with the correct schema. Or if you already have a crawl, you can use the CLI to load the data into a new table with:

`bq load --source_format=NEWLINE_DELIMITED_JSON my_dataset.my_new_table data.txt schema.json`

(Did that last one from memory, let me know if you try it and I got something wrong.)

**Comment by cstrouse** [comment]
Thanks @benjaminestes I was able to upload via the CLI with that command. The readme should probably mention something about that in the "Use with BigQuery" section.

**Comment by benjaminestes** [comment]
I will accept a pull request 🙏

**Comment by cstrouse** [comment]
Great. I'm working on improving that now. The web interface appears to have a SQL dialect toggle and to default to the standard dialect; however, I can only get it to load via the CLI.

![bigquery_query_settings](https://user-images.githubusercontent.com/849044/68917486-b4ffbf80-0727-11ea-97e8-2bbe385cf91d.png)


![bigquery_sql_dialect_toggle](https://user-images.githubusercontent.com/849044/68917458-93063d00-0727-11ea-85fd-9f354ca41f64.png)
